pipeline:
  build:
    when:
      event:
        branch: master
    image: python:alpine3.6
    commands:
      - python setup.py sdist

  publish:
    when:
      branch: master
    secrets:
      - docker_username
      - docker_password
      - ssh_key
    image: plugins/docker
    repo: mprescott/honeypy_report
    build_args_from_env:
      - SSH_KEY
