#!/bin/bash

printout() {
  printf "\n > ${1} \n\n"
}

printout "Building Python Module"

# package python module
python setup.py sdist

printout "Building Docker Image"

# build docker image
docker build --no-cache --build-arg SSH_KEY="$(cat ~/.ssh/deployment_key)" --build-arg PACKAGE=$1 -t mprescott/honeypy_report:latest .

printout "Pushing Docker Image to Docker Hub"
docker push mprescott/honeypy_report:latest
